# microservices components 1 - front
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather
  name: weather-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-front
  template:
    metadata:
      labels:
        app: weather-front
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: /actuator/prometheus          
    spec:
      containers:
        - image: brainupgrade/weather:latest
          imagePullPolicy: Always
          name: weather-front
          env:
            - name: spring.application.name
              value: weather-front
            - name: spring.datasource.url
              value: jdbc:mariadb://weather-db:3306/weather
            - name: spring.datasource.username
              value: weather
            - name: spring.datasource.password
              value: weather
            - name: weatherServiceURL
              value: http://weather-service
            - name: management.endpoints.web.exposure.include
              value: "*"
            - name: management.server.port
              value: "8888"
            - name: management.metrics.web.server.request.autotime.enabled
              value: "true"
            - name: management.metrics.tags.application
              value: weather-front              
          ports:
            - containerPort: 8080
